name: Deploy AKS-Construction

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/AKSC_Deploy.yml@0.9.10
    with:
      templateVersion: 0.9.10
      rg: az-k8s-eqj2-rg
      resourceName: az-k8s-eqj2
      templateParams: resourceName=az-k8s-eqj2 upgradeChannel=stable AksPaidSkuForSLA=true agentCountMax=20 custom_vnet=true enable_aad=true AksDisableLocalAccounts=true enableAzureRBAC=true adminPrincipalId=_USER_OBJECT_ID_ registries_sku=Premium acrPushRolePrincipalId=_USER_OBJECT_ID_ omsagent=true retentionInDays=30 ingressApplicationGateway=true appGWcount=0 appGWsku=WAF_v2 appGWmaxCount=10 keyVaultAksCSI=true keyVaultCreate=true keyVaultOfficerRolePrincipalId=_USER_OBJECT_ID_
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
